FROM node:lts-alpine as node

WORKDIR /code
COPY /ui/package.json /code/

RUN npm install

COPY /ui /code/

RUN npm run build

# Stage 0, based on Node.js, to build and compile Angular
FROM nginx:alpine
COPY ./template.nginx /etc/nginx/conf.d/template.nginx
COPY --from=docker.itgis.innovateteam.com/request_api:latest /code/static /usr/share/nginx/html/static
COPY --from=node /code/build/ /usr/share/nginx/html/ui