# Generated by Django 2.1.4 on 2018-12-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('possible_existing_account', models.CharField(blank=True, max_length=300, null=True)),
                ('organization', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('username_valid', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('creatorUT', 'Creator')], default='creatorUT', max_length=200)),
                ('role', models.CharField(choices=[('jmc1ObdWfBTH6NAN', 'EPA Publisher'), ('71yacZLdeuDirQ6K', 'EPA Viewer')], default='jmc1ObdWfBTH6NAN', max_length=200)),
                ('sponsor_notified', models.BooleanField(default=False)),
                ('recaptcha', models.TextField()),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('agol_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGOL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_url', models.URLField()),
                ('org_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AGOLGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('show', models.BooleanField(default=False, verbose_name='Show in multi-select')),
                ('agol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.AGOL')),
                ('requests', models.ManyToManyField(to='accounts.AccountRequests')),
            ],
        ),
        migrations.CreateModel(
            name='AGOLUserFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agol_username', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agol_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='groups',
            field=models.ManyToManyField(blank=True, to='accounts.AGOLGroup'),
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
