# Generated by Django 2.1.4 on 2019-09-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGOLGroupFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountrequests',
            options={'verbose_name': 'Account Request', 'verbose_name_plural': 'Account Requests'},
        ),
        migrations.AlterField(
            model_name='agolgroup',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Show in all multi-selects'),
        ),
        migrations.AddField(
            model_name='agolgroupfields',
            name='assignable_groups',
            field=models.ManyToManyField(blank=True, related_name='assignable_groups', to='accounts.AGOLGroup'),
        ),
        migrations.AddField(
            model_name='agolgroupfields',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
