# Generated by Django 2.2.7 on 2019-12-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190905_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoluserfields',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agoluserfields',
            name='region',
            field=models.CharField(choices=[('1', 'Region I - New England'), ('2', 'Region II - NJ, NY, Puerto Rico, US Virgin Islands'), ('3', 'Region III - Mid Atlantic'), ('4', 'Region IV - Southeast'), ('5', 'Region V - Great Lakes'), ('6', 'Region VI - Central South'), ('7', 'Region VII - IA, KS, MO, NE'), ('8', 'VIII - CO, MT, ND, SD, UT, WY'), ('9', 'Region IX - Pacific Southwest'), ('10', 'Region X - Pacific Northwest')], default='', max_length=200),
        ),
    ]
