# Generated by Django 2.2.7 on 2019-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190905_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='agoluserfields',
            name='authoritative_group',
            field=models.CharField(choices=[('R01', 'Region 1 - New England'), ('R02', 'Region 2 - NJ, NY, Puerto Rico, US Virgin Islands'), ('R03', 'Region 3 - Mid Atlantic'), ('R04', 'Region 4 - Southeast'), ('R05', 'Region 5 - Great Lakes'), ('R06', 'Region 6 - Central South'), ('R07', 'Region 7 - IA, KS, MO, NE'), ('R08', 'Region 8 - CO, MT, ND, SD, UT, WY'), ('R09', 'Region 9 - Pacific Southwest'), ('R10', 'Region 10 - Pacific Northwest'), ('OARM', 'EPA Office of Administration and Resources Management'), ('OAR', 'EPA Office of Air and Radiation'), ('OSCPP', 'EPA Office of Chemical Safety and Pollution Prevention'), ('OECA', 'EPA Office of Enforcement and Compliance Assurance'), ('OEI', 'EPA Office of Environmental Information'), ('OGC', 'EPA Office of General Counsel'), ('OIG', 'EPA Office of Inspector General'), ('OITA', 'EPA Office of International and Tribal Affairs'), ('OLEM', 'EPA Office of Land and Emergency Management'), ('ORD', 'EPA Office of Research and Development'), ('OW', 'EPA Office of Water'), ('OA', 'EPA Office of the Administrator'), ('OCFO', 'EPA Office of the Chief Financial Officer'), ('ER', 'OLEM - ER Program Support')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agoluserfields',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
