# Generated by Django 2.2.12 on 2020-05-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191210_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequests',
            options={'permissions': [('view_all_accountrequests', 'Can view ALL Account Requests regardless of Sponsor')], 'verbose_name': 'Account Request', 'verbose_name_plural': 'Account Requests'},
        ),
    ]
