# Generated by Django 2.2.12 on 2020-06-16 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0006_auto_20200508_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGOLRole',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('agol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.AGOL')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Response/Project',
                'verbose_name_plural': 'Responses/Projects',
            },
        ),
        migrations.RemoveField(
            model_name='agolgroup',
            name='show',
        ),
        migrations.RemoveField(
            model_name='agoluserfields',
            name='authoritative_group',
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AGOLGroup'),
        ),
        migrations.AddField(
            model_name='agolgroup',
            name='is_auth_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='account_requests', to='accounts.AGOLGroup'),
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AGOLRole'),
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agoluserfields',
            name='delegates',
            field=models.ManyToManyField(related_name='delegate_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AGOLGroupFields',
        ),
        migrations.AddField(
            model_name='responseproject',
            name='assignable_groups',
            field=models.ManyToManyField(related_name='response', to='accounts.AGOLGroup', verbose_name='GeoPlatform Assignable Groups'),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='authoritative_group',
            field=models.ForeignKey(limit_choices_to={'is_auth_group': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.AGOLGroup', verbose_name='Geoplatform Authoritative Group'),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='groups',
            field=models.ManyToManyField(related_name='response', to='auth.Group', verbose_name='Response/Project Group'),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.AGOLRole', verbose_name='GeoPlatform Role'),
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.ResponseProject'),
        ),
    ]
