# Generated by Django 2.2.12 on 2020-06-17 02:56

from django.db import migrations, models
import django

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200616_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequests',
            name='role',
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='accounts.AGOLRole'),
        ),
    ]
