# Generated by Django 2.2.12 on 2020-06-25 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_remove_accountrequests_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseproject',
            name='groups',
        ),
        migrations.AddField(
            model_name='responseproject',
            name='users',
            field=models.ManyToManyField(limit_choices_to={'agol_info__sponsor': True}, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='Approving Users'),
        ),
        migrations.AlterField(
            model_name='agoluserfields',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='delegate_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
