# Generated by Django 2.2.12 on 2020-06-25 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200625_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequests',
            name='description',
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='users',
            field=models.ManyToManyField(limit_choices_to={'agol_info__sponsor': True}, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='Sponsors'),
        ),
    ]
