# Generated by Django 2.2.7 on 2021-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200625_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequests',
            name='is_existing_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
