# Generated by Django 2.2.12 on 2021-02-19 21:39

from django.db import migrations, models
import django.db.models.deletion

def transfer_relationship_records(apps, schema_editor):
    AccountRequests = apps.get_model('accounts', 'AccountRequests')
    GroupMembership = apps.get_model('accounts', 'GroupMembership')
    for ar in AccountRequests.objects.all():
        for rel in ar.groups.through.objects.all():
            GroupMembership.objects.update_or_create(group=rel.agolgroup, request=rel.accountrequests)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210217_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AGOLGroup')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountRequests')),
            ],
        ),
        migrations.RunPython(transfer_relationship_records)
    ]
