# Generated by Django 2.2.12 on 2021-02-19 21:47

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_groupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequests',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='agolgroup',
            name='requests',
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='temp_groups',
            field=models.ManyToManyField(blank=True, related_name='account_requests', through='accounts.GroupMembership', to='accounts.AGOLGroup'),
        ),
        migrations.AddField(
            model_name='agolgroup',
            name='temp_requests',
            field=models.ManyToManyField(through='accounts.GroupMembership', to='accounts.AccountRequests'),
        ),
        migrations.RenameField(
            model_name='accountrequests',
            old_name='temp_groups',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='agolgroup',
            old_name='temp_requests',
            new_name='requests',
        ),
    ]
