# Generated by Django 2.2.24 on 2021-12-06 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import now


def set_existing_repsonses_to_approved(apps, schema_editor):
    ResponseProject = apps.get_model('accounts', 'ResponseProject')
    for r in ResponseProject.objects.all():
        r.approved = now()
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_responseproject_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseproject',
            name='is_disabled',
        ),
        migrations.AddField(
            model_name='agolrole',
            name='system_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='disabled',
            field=models.DateTimeField(blank=True, help_text='Disabling will send an email notification to assigned sponsors and their delegates.', null=True),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disabled_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='default_reason',
            field=models.CharField(choices=[('Emergency Response', 'Emergency Response'), ('Other Federal Agency', 'Other Federal Agency'), ('State Agency', 'State Agency'), ('University', 'University'), ('Long Term GIS Support', 'Long Term GIS Support'), ('Non Government Organization', 'Non Government Organization'), ('Tribal Government', 'Tribal Government'), ('Citizen Advisor', 'Citizen Advisor'), ('Other', 'Other')], max_length=200, verbose_name='Default Reason / Affiliation'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(blank=True, help_text='System default will be used if left blank.', limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.AGOLRole', verbose_name='GeoPlatform Role'),
        ),
        migrations.RunPython(set_existing_repsonses_to_approved, migrations.RunPython.noop)
    ]
