# Generated by Django 2.2.24 on 2021-12-07 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0015_auto_20211206_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequests',
            name='sponsor_notified',
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='disabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'agol_info__sponsor': True}, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='Sponsors'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
