# Generated by Django 2.2.24 on 2021-12-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211207_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agoluserfields',
            name='phone_number',
        ),
    ]
