# Generated by Django 2.2.24 on 2021-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_agoluserfields_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequests',
            name='existing_account_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
