# Generated by Django 2.2.24 on 2021-12-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_accountrequests_existing_account_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
