# Generated by Django 2.2.24 on 2021-12-10 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_auto_20211210_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequests',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
