# Generated by Django 4.1.6 on 2023-02-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_pk_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol',
            name='portal_name',
            field=models.CharField(choices=[('geosecure', 'Geosecure'), ('geoplatform', 'Geoplatform')], blank=True, null=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agoluserfields',
            name='portal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='auth_provider', to='accounts.agol'),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='portal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.agol'),
        ),
    ]
