# Generated by Django 4.1.7 on 2023-03-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_agol_portal_name_agoluserfields_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agol',
            name='portal_name',
            field=models.CharField(blank=True, choices=[('geosecure', 'GeoSecure'), ('geoplatform', 'GeoPlatform')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agoluserfields',
            name='portal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.agol'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='authoritative_group',
            field=models.ForeignKey(limit_choices_to={'is_auth_group': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.agolgroup', verbose_name='Authoritative Group'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(blank=True, help_text='System default will be used if left blank.', limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.agolrole', verbose_name='GeoPlatform Role'),
        ),
    ]
