# Generated by Django 4.1.9 on 2023-06-05 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_alter_agol_portal_name_alter_agoluserfields_portal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agoluserfields',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.agol'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='assignable_groups',
            field=models.ManyToManyField(related_name='response', to='accounts.agolgroup', verbose_name='Assignable Groups'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.agol'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(blank=True, help_text='System default will be used if left blank.', limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.agolrole', verbose_name='Role'),
        ),
    ]
