# Generated by Django 4.1.9 on 2023-06-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_accountrequests_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequests',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_requests', to='accounts.agolrole'),
        ),
        migrations.AlterField(
            model_name='agolrole',
            name='agol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.agol'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(blank=True, help_text='System default will be used if left blank.', limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='accounts.agolrole', verbose_name='Role'),
        ),
    ]
