# Generated by Django 4.1.9 on 2023-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_accountrequests_role_alter_agolrole_agol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol',
            name='allow_external_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agol',
            name='enterprise_precreate_domains',
            field=models.TextField(null=True),
        ),
    ]
