# Generated by Django 4.1.9 on 2023-10-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_agol_allow_external_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agolrole',
            name='auth_groups',
            field=models.ManyToManyField(related_name='roles', to='accounts.agolgroup'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='accounts.agol', verbose_name='Portal/AGOL'),
        ),
    ]
