# Generated by Django 4.2.7 on 2023-11-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_agolrole_auth_groups_alter_responseproject_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol',
            name='requires_auth_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agolrole',
            name='auth_groups',
            field=models.ManyToManyField(limit_choices_to={'is_auth_group': True}, related_name='roles', to='accounts.agolgroup', verbose_name='Allowed Authoritative Groups'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='role',
            field=models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='accounts.agolrole', verbose_name='Role'),
        ),
    ]
