# Generated by Django 4.2.7 on 2023-12-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_agol_requires_auth_group_alter_agolrole_auth_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='username',
            field=models.CharField(help_text='User frontend to modify username.', max_length=200),
        ),
        migrations.AddField(
            model_name='responseproject',
            name='protected_datasets',
            field=models.ManyToManyField(to='accounts.protecteddataset'),
        ),
    ]
