# Generated by Django 4.2.16 on 2024-09-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_responseproject_protected_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='agolgroup',
            name='users',
            field=models.ManyToManyField(through='accounts.GroupMembership', to='accounts.agoluserfields'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agoluserfields'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountrequests'),
        ),
        migrations.AlterField(
            model_name='responseproject',
            name='protected_datasets',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.protecteddataset'),
        ),
    ]
