# Generated by Django 4.2.16 on 2025-01-06 23:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_agolgroup_users_groupmembership_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol',
            name='email_signature_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
