# Generated by Django 4.2.16 on 2025-01-07 22:44

from django.db import migrations, models
import django.db.models.deletion

def convert_user_types(apps, schema_editor):
    UserType = apps.get_model('accounts', 'UserType')
    AccountRequests = apps.get_model('accounts', 'AccountRequests')
    creator = UserType.objects.create(code='creatorUT', name='Creator')

    AccountRequests.objects.filter(user_type='creatorUT').update(new_user_type=creator)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_agolgroup_users_groupmembership_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AGOL/Portal User Type',
                'verbose_name_plural': 'AGOL/Portal User Types',
            },
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='new_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usertype'),
        ),
        migrations.RunPython(convert_user_types),
        migrations.RemoveField(
            model_name='accountrequests',
            name='user_type',
        ),
        migrations.RenameField(
            model_name='accountrequests',
            old_name='new_user_type',
            new_name='user_type',
        ),
    ]
