# Generated by Django 4.2.16 on 2025-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_usertype_accountrequests_new_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='hierarchy',
            field=models.IntegerField(default=0, help_text='This controls if a users account needs to be given a higher user type when approved than what they currently have so that it is compatible with the roles they are assigned to.'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='compatible_roles',
            field=models.ManyToManyField(related_name='user_types', to='accounts.agolrole'),
        ),
    ]
