# Generated by Django 4.2.16 on 2025-01-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_usertype_accountrequests_new_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseproject',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='accounts.usertype'),
            preserve_default=False,
        ),
    ]
