# Generated by Django 4.2.16 on 2025-11-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_agol_email_signature_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agol',
            options={'verbose_name': 'AGOL/Portal', 'verbose_name_plural': 'AGOL/Portals'},
        ),
        migrations.AlterModelOptions(
            name='agolgroup',
            options={'verbose_name': 'AGOL/Portal Group', 'verbose_name_plural': 'AGOL/Portal Groups'},
        ),
        migrations.AlterModelOptions(
            name='agolrole',
            options={'verbose_name': 'AGOL/Portals Role', 'verbose_name_plural': 'AGOL/Portals Roles'},
        ),
        migrations.RemoveField(
            model_name='agol',
            name='user',
        ),
        migrations.AddField(
            model_name='agol',
            name='token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='agol',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
