# Generated by Django 4.2.16 on 2025-01-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_responseproject_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='portal',
            field=models.ManyToManyField(related_name='user_types', to='accounts.agol'),
        ),
    ]
