# Generated by Django 4.2.16 on 2026-07-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_usertype_accountrequests_new_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agol',
            name='default_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_portals', to='accounts.usertype'),
        ),
    ]

