# Generated by Django 4.2.16 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_usertype_accountrequests_new_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='system_default',
            field=models.BooleanField(default=False),
        ),
    ]

